#!/usr/bin/env bash
# Bump the project version across every manifest in lockstep, then
# (optionally) create a git tag that triggers the GitHub Actions
# release workflow. This is the local-dev equivalent of the
# workflow's tag-driven trigger — running this script is what you
# do right before `git push --tags`.
#
# What this script touches:
#   - package.json
#   - src-tauri/tauri.conf.json
#   - src-tauri/Cargo.toml
#   - crates/engine/Cargo.toml
#   - crates/native-host/Cargo.toml
#   - browser-extension/manifest.json
#   - crates/native-host/Cargo.toml (workspace member, but not a
#     separately versioned package — we still bump it so the
#     release artifacts have a matching version stamp)
#
# What this script does NOT touch:
#   - Cargo.lock         (regenerated by `cargo check` post-bump;
#                          we run it ourselves at the end)
#   - dist/, target/     (build outputs)
#   - Any other JSON/Yaml that mentions a version
#
# Usage:
#   ./scripts/release.sh 0.1.0
#   ./scripts/release.sh 0.2.0-rc.1
#   ./scripts/release.sh 0.1.1 --no-tag    # bump only, no git tag
#   ./scripts/release.sh --current         # print the current version
#
# Exit codes:
#   0  bump (and optionally tag) succeeded
#   1  invalid args
#   2  not a git repo / not on main
#   3  working tree dirty
#   4  version is not a valid semver string
#   5  one of the bumps failed

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# ── arg parsing ──────────────────────────────────────────────────────
NO_TAG=0
PRINT_CURRENT=0
VERSION=""

usage() {
  sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
  -h | --help) usage ;;
  --no-tag)
    NO_TAG=1
    shift
    ;;
  --current)
    PRINT_CURRENT=1
    shift
    ;;
  -*)
    echo "unknown flag: $1" >&2
    exit 1
    ;;
  *)
    [[ -n "$VERSION" ]] && {
      echo "error: multiple versions provided" >&2
      exit 1
    }
    VERSION="$1"
    shift
    ;;
  esac
done

# ── current version helper ──────────────────────────────────────────
read_current_version() {
  # The canonical version lives in package.json (the frontend's
  # package.json is the most-edited manifest during dev). If a
  # previous bump left the manifests out of sync we report the
  # mismatch but still use package.json's value as truth.
  node -e 'process.stdout.write(JSON.parse(require("fs").readFileSync("package.json","utf8")).version)'
}

if [[ $PRINT_CURRENT -eq 1 ]]; then
  echo "current version: $(read_current_version)"
  exit 0
fi

if [[ -z "$VERSION" ]]; then
  echo "usage: $0 <version> [--no-tag]" >&2
  echo "       $0 --current" >&2
  exit 1
fi

# Strip a leading "v" — tags like "v0.1.0" are fine on the command
# line but the manifests must use a bare semver.
VERSION="${VERSION#v}"

# Semver-ish check: MAJOR.MINOR.PATCH with optional -prerelease.
# We don't enforce a strict SemVer 2.0.0 (no "+build" metadata) but
# we do require the three numeric parts; the prerelease suffix is
# free-form because the Tauri/extension manifests accept anything
# that looks like "0.1.0-rc.1".
if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9._-]+)?$ ]]; then
  echo "error: \"$VERSION\" is not a valid version (expected MAJOR.MINOR.PATCH with optional -suffix)" >&2
  exit 4
fi

CURRENT="$(read_current_version)"
echo "current: $CURRENT → new: $VERSION"

# ── pre-flight checks ────────────────────────────────────────────────
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "error: not a git repo" >&2
  exit 2
fi

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$BRANCH" != "main" && "$BRANCH" != "master" && $NO_TAG -eq 0 ]]; then
  echo "warning: you are on '$BRANCH', not main/master. Tagging from a non-main branch is allowed but unusual." >&2
  echo "         press Ctrl-C in the next 5s to abort, or wait to continue." >&2
  sleep 5
fi

# Refuse to bump on a dirty tree — otherwise the version commit
# will absorb whatever unrelated edits are in progress.
if ! git diff --quiet HEAD 2>/dev/null; then
  echo "error: working tree has uncommitted changes. Commit or stash them first." >&2
  git status --short
  exit 3
fi

# ── bump ─────────────────────────────────────────────────────────────
# We use node for the JSON manifests because jq is sometimes missing
# on minimal CI images, and python isn't always on PATH either. node
# is a hard dep for the frontend so it's guaranteed to be there.

bump_json() {
  local file="$1"
  local key="$2"
  node -e "
    const fs = require('fs');
    const f = process.argv[1];
    const obj = JSON.parse(fs.readFileSync(f, 'utf8'));
    const keys = process.argv[2].split('.');
    let cur = obj;
    for (let i = 0; i < keys.length - 1; i++) cur = cur[keys[i]];
    cur[keys[keys.length - 1]] = process.argv[3];
    fs.writeFileSync(f, JSON.stringify(obj, null, 2) + '\n');
  " "$file" "$key" "$VERSION"
}

bump_toml_version() {
  # Matches the first `version = "..."` line under [package]. We
  # only expect one in each Cargo.toml so a naive sed is fine.
  local file="$1"
  python3 -c "
    import re, sys
    p = '$file'
    with open(p) as f: t = f.read()
    new = re.sub(r'(^\[package\][^\[]*?^version\s*=\s*\")[^\"]*(\")',
                 r'\g<1>$VERSION\g<2>', t, count=1, flags=re.M | re.S)
    if new == t:
      print('error: no [package] version found in', p, file=sys.stderr); sys.exit(1)
    with open(p, 'w') as f: f.write(new)
  " || {
    echo "bump failed in $file" >&2
    exit 5
  }
}

echo "→ package.json"
bump_json package.json version
echo "→ src-tauri/tauri.conf.json"
bump_json src-tauri/tauri.conf.json version
echo "→ src-tauri/Cargo.toml"
bump_toml_version src-tauri/Cargo.toml
echo "→ crates/engine/Cargo.toml"
bump_toml_version crates/engine/Cargo.toml
echo "→ crates/native-host/Cargo.toml"
bump_toml_version crates/native-host/Cargo.toml
echo "→ browser-extension/manifest.json"
bump_json browser-extension/manifest.json version

# ── regenerate Cargo.lock so it matches the new versions ─────────────
echo "→ regenerating Cargo.lock"
cargo check --workspace --quiet 2>/dev/null || cargo check --workspace

# ── git commit + tag ─────────────────────────────────────────────────
if [[ $NO_TAG -eq 1 ]]; then
  echo
  echo "✔ version bumped to $VERSION (--no-tag: no commit/tag created)"
  echo "  review the changes and commit them yourself when ready."
else
  git add package.json src-tauri/tauri.conf.json \
    src-tauri/Cargo.toml crates/engine/Cargo.toml \
    crates/native-host/Cargo.toml Cargo.lock \
    browser-extension/manifest.json
  git commit -m "chore(release): v$VERSION"

  # The tag MUST be "v<version>" — the release.yml workflow filters on `v*`.
  git tag -a "v$VERSION" -m "Release v$VERSION"
  echo
  echo "✔ tagged v$VERSION"
  echo "  push with:   git push origin $BRANCH --follow-tags"
  echo "  or review:   git show v$VERSION"
fi
